title: Aperoláda I. a jeho vesmír
author: I536470
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Aperoláda Šmakuláda má svůj blog, kde se můžete dozvědět nejnovější informace o jeho životě!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
